# Generated by Django 2.1.5 on 2019-01-07 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_auto_20190107_2329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=4, max_digits=14)),
                ('fecha_emision', models.DateField()),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_limite_pago', models.DateField()),
                ('monto_pagado', models.DecimalField(decimal_places=4, max_digits=14)),
                ('xml', models.FileField(upload_to='')),
                ('credito', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.TipoCredito')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.EstadoFactura')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.TipoMoneda')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=4, max_digits=14)),
                ('fecha', models.DateField()),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egresos.Factura')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=250)),
                ('descripcion', models.CharField(max_length=250)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('categoria_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.CategoriaTipoProveedor')),
            ],
        ),
        migrations.AddField(
            model_name='factura',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egresos.Proveedor'),
        ),
    ]
