# Generated by Django 2.1.5 on 2019-01-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egresos', '0002_auto_20190108_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='monto_pagado',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
    ]
