# Generated by Django 2.1.5 on 2019-01-09 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('egresos', '0003_auto_20190108_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='credito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.TipoCredito'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.EstadoFactura'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='moneda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.TipoMoneda'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='egresos.Proveedor'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='factura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='egresos.Factura'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='categoria_proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.CategoriaTipoProveedor'),
        ),
    ]
