# Generated by Django 2.1.5 on 2019-01-09 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('egresos', '0004_auto_20190109_0341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedor',
            options={'verbose_name_plural': 'Proveedores'},
        ),
    ]
