# Generated by Django 2.1.5 on 2019-01-10 05:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egresos', '0005_auto_20190109_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='email_contacto',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='rfc',
            field=models.CharField(default='RFC', max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='El R.F.C. debe tener 13 caracteres.', regex='^.{13}$')]),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='telefono_contacto',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
