# Generated by Django 2.1.5 on 2019-01-12 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egresos', '0008_auto_20190112_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='email_contacto',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono_contacto',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
