# Generated by Django 2.1.5 on 2019-01-12 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_tipounidad'),
        ('egresos', '0009_auto_20190112_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concepto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_prod_serv', models.CharField(max_length=250)),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=14)),
                ('descripcion', models.CharField(max_length=250)),
                ('valor_unitario', models.DecimalField(decimal_places=4, max_digits=14)),
                ('importe', models.DecimalField(decimal_places=4, max_digits=14)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conceptos', to='egresos.Factura')),
                ('unidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.TipoUnidad')),
            ],
        ),
    ]
