# Generated by Django 2.1.5 on 2019-01-12 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_tipounidad'),
        ('egresos', '0010_concepto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='categoria_proveedor',
        ),
        migrations.AddField(
            model_name='factura',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.CategoriaTipoProveedor'),
        ),
    ]
