# Generated by Django 2.1.5 on 2019-01-12 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('egresos', '0011_auto_20190112_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas', to='egresos.Proveedor'),
        ),
    ]
