# Generated by Django 2.1.5 on 2019-01-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egresos', '0012_auto_20190112_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='xml',
            field=models.FileField(blank=True, null=True, upload_to='facturas/'),
        ),
    ]
