# Generated by Django 2.1.5 on 2019-01-18 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('egresos', '0014_auto_20190117_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='factura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='egresos.Factura'),
        ),
    ]
