# Generated by Django 2.1.5 on 2019-09-07 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('egresos', '0015_auto_20190118_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='credito',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='fecha_alta',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='fecha_emision',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='fecha_limite_pago',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='fecha_ultima_modificacion',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='moneda',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='monto',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='monto_pagado',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='proveedor',
        ),
    ]
