# Generated by Django 2.1.5 on 2019-09-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egresos', '0016_auto_20190907_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='concepto',
            name='descuento_maximo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='concepto',
            name='precio_venta_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
