# Generated by Django 2.1.5 on 2019-01-07 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190107_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriatipoproveedor',
            name='tipo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.TipoProveedor'),
            preserve_default=False,
        ),
    ]
