# Generated by Django 2.1.5 on 2019-01-09 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190108_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriatipoproveedor',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorias', related_query_name='categoria', to='main.TipoProveedor'),
        ),
        migrations.AlterField(
            model_name='tipocambiomoneda',
            name='moneda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.TipoMoneda'),
        ),
    ]
