# Generated by Django 2.1.5 on 2019-01-17 05:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_tipounidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='rfc',
            field=models.CharField(default='RFC', max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='El R.F.C. debe tener 12 o 13 caracteres.', regex='^.{12,13}$')]),
        ),
    ]
